// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3GTQhlqWzxa5jyGnjZ-NYsBhwyxzIE5U',
    appId: '1:1095499081927:web:52ea5121fba4f0b08336e2',
    messagingSenderId: '1095499081927',
    projectId: 'my-flow-track',
    authDomain: 'my-flow-track.firebaseapp.com',
    storageBucket: 'my-flow-track.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_zx-_7KtW6MoAUxTZ7Nqa-smMEMQOcXM',
    appId: '1:1095499081927:android:dd1080f32d87e2e58336e2',
    messagingSenderId: '1095499081927',
    projectId: 'my-flow-track',
    storageBucket: 'my-flow-track.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALZOMLCwVU31vhTbA0snN62JC_Ez_J4Lc',
    appId: '1:1095499081927:ios:41ae275bfd456af58336e2',
    messagingSenderId: '1095499081927',
    projectId: 'my-flow-track',
    storageBucket: 'my-flow-track.appspot.com',
    iosBundleId: 'com.example.flowtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALZOMLCwVU31vhTbA0snN62JC_Ez_J4Lc',
    appId: '1:1095499081927:ios:41ae275bfd456af58336e2',
    messagingSenderId: '1095499081927',
    projectId: 'my-flow-track',
    storageBucket: 'my-flow-track.appspot.com',
    iosBundleId: 'com.example.flowtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3GTQhlqWzxa5jyGnjZ-NYsBhwyxzIE5U',
    appId: '1:1095499081927:web:007be9d8e4eb03128336e2',
    messagingSenderId: '1095499081927',
    projectId: 'my-flow-track',
    authDomain: 'my-flow-track.firebaseapp.com',
    storageBucket: 'my-flow-track.appspot.com',
  );
}
